#!/bin/bash
echo "🚀 VERCEL DEPLOYMENT COMMANDS"
echo "================================"
echo ""
echo "1. AUTHENTICATE WITH VERCEL:"
echo "   vercel login"
echo ""
echo "2. DEPLOY TO PRODUCTION:"
echo "   vercel --prod"
echo ""
echo "3. TEST DEPLOYMENT:"
echo "   # Replace YOUR_APP_URL with actual Vercel URL"
echo "   curl https://YOUR_APP_URL.vercel.app/api/health"
echo ""
echo "4. TEST CORS FOR IRANIAN ACCESS:"
echo "   curl -H 'Origin: https://aminchedo.github.io' \\"
echo "        -H 'Access-Control-Request-Method: POST' \\"
echo "        -X OPTIONS \\"
echo "        https://YOUR_APP_URL.vercel.app/api/health"
echo ""
echo "🎯 EXPECTED HEALTH RESPONSE:"
echo '{"status":"OK","message":"سرویس فعال است"}'
echo ""
echo "✅ DEPLOYMENT FIX COMPLETE!"
