[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  VITE_API_URL = "https://iranian-legal-archive-backend.railway.app/api"
  VITE_WS_URL = "wss://iranian-legal-archive-backend.railway.app/ws"

[[redirects]]
  from = "/api/*"
  to = "https://iranian-legal-archive-backend.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"